#!/usr/bin/env bash
# A Bash script that loops forever and prints a message when receiving SIGTERM

# Print on SIGTERM and keep running
trap 'echo "I am invincible!!!"' TERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
